# Generated by Django 3.2.4 on 2021-06-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Type', to='blogs.blogtype', to_field='name'),
        ),
    ]
