# Generated by Django 3.2.4 on 2021-06-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='power',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
