# Generated by Django 3.2.4 on 2021-06-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_tags',
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True, unique=True)),
                ('answer', models.CharField(max_length=255, null=True, unique=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blogs.blog')),
            ],
        ),
    ]
