# Generated by Django 3.2.4 on 2021-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210627_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='blogs.BlogTags'),
        ),
    ]
