# Generated by Django 3.2.5 on 2021-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='page_title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=1000),
        ),
    ]
