# Generated by Django 3.2.5 on 2021-07-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210708_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=3000),
        ),
    ]
