# Generated by Django 3.2.5 on 2021-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='page_title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
