# Generated by Django 3.2.5 on 2021-07-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20210712_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='uuid',
            new_name='id',
        ),
    ]
